- name: download repo file
  get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: install vault
  dnf:
    name: vault
    state: installed

- name: enable http in vault.hcl file
  copy:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: start vault service
  systemd_service:
    name: vault
    state: started
    enabled: true