- name: download the docker repo file
  get_url: 
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install the docker in vm
  dnf:
    name: docker-ce
    state: installed

- name: add user to docker to avoid sudo issue
  user:
    name: harshal
    groups: docker
    append: yes
    
- name: start docker on vm
  systemd_service:
    name: docker
    state: started
    enabled: true

- name: create runner containers 
  loop:
    - runner-1
    - runner-2
    - runner-3
  community.docker.docker_container:
    name: "{{ item }}"
    image: rkalluru/d84-github-runner
    state: started 
    pull: always
    restart: true
    env:
      ORG: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/github-runner:ORG token={{ token }} url=http://vault-int.harshaldevops.online:8200') }}"
      TOKEN: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/github-runner:TOKEN token={{ token }} url=http://vault-int.harshaldevops.online:8200') }}"
      NAME: "{{ item }}"