- name: download the docker repo file
  get_url: 
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install the docker in vm
  dnf:
    name: docker-ce
    state: installed

- name: add user to docker to avoid sudo issue
  user:
    name: harshal
    groups: docker
    append: yes

# - name: set docker .sock file permission 
#   shell: chmod o+rw /var/run/docker.sock

- name: set docker .xock file permission at boot
  template:
    src: docker.service
    dest: /usr/lib/systemd/system/docker.service

- name: start docker on vm
  systemd_service:
    name: docker
    state: restarted
    enabled: true
    daemon-reload: true

- name: Get Runner token
  shell: |
    gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/Harshal-HP/actions/runners/registration-token | jq -r .token
  become: yes
  become_user: harshal
  delegate_to: localhost
  register: gh_org_token

- name: create runner containers 
  loop:
    - runner-1
    - runner-2
  community.docker.docker_container:
    name: "{{ item }}"
    image: harshalhp/github-runner
    state: started 
    pull: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: true
    restart_policy: always
    env:
      ORG: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/github-runner:ORG token={{ token }} url=http://vault-int.harshaldevops.online:8200') }}"
      TOKEN: "{{ gh_org_token.stdout }}"
      NAME: "{{ item }}"
      ARM_CLIENT_ID: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_CLIENT_ID token={{ token }} url=http://vault-int.harshaldevops.online:8200') }}"
      ARM_CLIENT_SECRET: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_CLIENT_SECRET token={{ token }} url=http://vault-int.harshaldevops.online:8200') }}"
      ARM_TENANT_ID: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_TENANT_ID token={{ token }} url=http://vault-int.harshaldevops.online:8200') }}"